### PR TITLE
Generate types

### PR DESCRIPTION
**Pull request by FredricW**
Hi!

I wanted to start using this library and noticed that it is written in Typescript, but doesn't really expose the types.
So I made some changes to make that happen in case you want to accept it!

**Changes:**
* Updated all dependencies to latest
  * This resulted in a slightly updated build command due to `webpack` now at v5 :)
* Removed the deprecated `zlib` package
* Added polyfill (`node-polyfill-webpack-plugin`) to fix the missing utilities
* Removed the `prepublish` script as I was not able to run `npm install` successfully while it was in place (not really sure why)
* Added the ability to generate types and expose them 
  * Unfortunately, types seems to also be generated for files outside the `/src` folder which I didn't really find a quick solution for
* Fixed a type error that appeared in `src/index.ts` due to a missing type export
* Regenerated the `package.lock` file
  * Some sub dependencies had a conflict and I was only able to resolve it by regenerating the whole file

**Some notes:**
* I did not look too much into what happened between v5 and v10 of `mocha`, but it looked to me like all the tests still worked fine.
* Not sure what version of Node you were using, but everything should work fine on the current LTS version now (`18.x`)
* If you think there are too many changes at once here I could split up the dependency updates and the type generation into 

I guess you would need to take care of bumping the version and publish it.

### CODE REVIEW

**Comment by FredricW** [comment]
Btw, ff you need the `prepublish` script to stay in order for Travis to work, I can add it back in!

**Comment by demipixel** [comment]
Looks good! Not too concerned as long as it still builds and tests pass.

Could we convert `prepublish` to `prepublishOnly`? Just want to make sure I never publish without latest build and tests passing.

**Comment by FredricW** [comment]
Yeah for sure!

**Comment by demipixel** [comment]
Thanks so much for this!

v2.6.0 is published.

**Pull request merged**
