### PR TITLE
Multiple Blueprint unit tests.

### PR DESCRIPTION
**Pull request by CandleCandle**
Add many unit tests prior to refactoring and #32.

Known Issues:
implementation of `constant-combiner` behaviour and `filter-inserter` behaviour conflicts. Reverted some of the `parseFilters` implementation until there's a simple unit test for `constant-combiner`s (I rebased my changes onto master and my `filter-inserter` test started failing!)

Two unit test frameworks: I used with mocha as converting one test to use mocha was easier than converting all of mine. Should pick one, and remove the other.

Lots of gaps that need simple blueprints from in-game and assertions adding.

### CODE REVIEW

**Comment by demipixel** [comment]
Accidentally closed it, whoops :P

So, I noticed

```js
assert.equal(obj.blueprint.entities[0].filters[0].index, 1); // TODO possible bug here; the parse test has it indexed from 0.
```

Not sure what the issue is? The array index (`filters[i]`) when handled by Factorio means nothing, it only looks at the index.

**Comment by demipixel** [comment]
Do you think this PR is ready for merging?

**Comment by CandleCandle** [comment]
I think it *can* be. There are some stub tests (e.g. tests that need sample blueprints from in-game) and some tests that attempt to demonstrate features that are missing (e.g. train stop circuit conditions).

I think that in hindsight, it will be ready when the first problem is complete (stub tests). The second (missing features) should be much easier with (a) the set of tests and (b) the change to how entities are handled that I have a prototype for - I'll try to push that to a branch in my fork so that you can have a look at it; It's far from complete, and that branch is highly likely to have force-pushes to it though.

**Comment by CandleCandle** [comment]
Found some more missing features, added tests that can demonstrate them; filled in the remaining stub tests.

If you are happy with the changes, I think that now it is ready to merge.

**Comment by demipixel** [comment]
Thank you so, so much!

**Pull request merged**
