### PR TITLE
Task/nodejs build

### PR DESCRIPTION
**Pull request by blacha**
Compile a ESM & CommonJs version for NPM.

I have marked this as a draft, as I need to do some more verification of the build process, eg  how do these changes affect another lib webpacking this repo. I have only really been testing with other TS/NodeJs libs

As part of this I have correct a few minor typing issues

It also looks like my npm `v6.9.0` adds a `dev: true` and `optional: true` If this is a problem, I can downgrade to what ever version you use.

### CODE REVIEW

**Comment by blacha** [comment]
@demipixel I am having some issues with the typings due to how everything is packaged and exported.

Using `export default class Blueprint {}` creates a `exports.default = Blueprint;`

which allows these two styles of imports for the typings to align
```
import Blueprint from 'factorio-blueprint'
const Blueprint = require('factorio-blueprint').default
```
since the package is currently exported as a umd module, you can require it without the `.default` however typescript will not pick up the typings. 

I am not personally a huge fan of default exports they have been a cause of many errors in my code bases, I prefer to use named exports

```
export class Blueprint {}

import {Blueprint} from 'factorio-blueprint'
const {Blueprint} = require('factorio-blueprint')
```

Are you open to changing the exporting style? Or do you have any ideas on how to align the types

**Comment by demipixel** [comment]
I think the latter is fine, however it will likely require a major version change since it would pretty much break every existing project.

**Comment by slikts** [comment]
> I am not personally a huge fan of default exports they have been a cause of many errors in my code bases ...

Default exports shouldn't be an issue in TypeScript.

**Comment by blacha** [comment]
> Default exports shouldn't be an issue in TypeScript.

They work as expected in Typescript. Its more how they interact with multiple developers regarding refactoring, tree shaking and naming standards. 

There was a discussion around their use within the airbnb coding style and the pros/cons here https://github.com/airbnb/javascript/issues/1365

> I think the latter is fine, however it will likely require a major version change since it would pretty much break every existing project.

I will update the PR to export Blueprint as a named export.

**Comment by slikts** [comment]
I'm familiar with that thread and it doesn't support the view that default exports would cause errors, and it doesn't make a particularly strong case against default exports in general; certainly not strong enough to break backwards compatibility over.

**Comment by blacha** [comment]
The goal here is to fix the types.  Is there a better way of making the types usable?

It would be advantageous to allow future expansion, like extending Blueprint book support or exposing more types.

With named exports this becomes very easy
`import { Tile, Blueprint, Entity, BlueprintBook, BlueprintJson } from 'factorio-blueprint';`

**Pull request closed without merging**
